name: 'Label issues'
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Automatically marked uncategorized issue as product feedback'
          stale-issue-label: 'product-feedback'
          exempt-issue-labels: 'doc-bug,doc-enhancement,doc-idea,product-issue,product-question'
          days-before-issue-stale: 0
